### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by LucaBarbaLata** [Raptor123471/DingoLingo#125]
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Proiecte py\DingoLingo-master\run.py", line 84, in <module>
    bot.run(config.BOT_TOKEN, bot=True, reconnect=True)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 717, in run
    return future.result()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 696, in runner
    await self.start(*args, **kwargs)
TypeError: Client.start() got an unexpected keyword argument 'bot'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002AA8C046BF0>

**Comment by solaluset** [comment]
Please see https://github.com/Raptor123471/DingoLingo/issues/110#issuecomment-1185770275

**Comment by hishu9999** [comment]
change bot.run(config.BOT_TOKEN, bot=True, reconnect=True) to bot.run(config.BOT_TOKEN)
