### ISSUE TITLE
Cant play music:       ClientException: ffmpeg was not found.

### ISSUE THREAD

**Issue by xaitzx** [Raptor123471/DingoLingo#133]
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/discord/ext/commands/bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/discord/ext/commands/core.py", line 1029, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/discord/ext/commands/core.py", line 244, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ClientException: ffmpeg was not found.

**Comment by solaluset** [comment]
You need to download FFmpeg and put it where the bot can find it (for example, bot directory).

If you're using Windows, [my fork](https://github.com/Krutyi-4el/DandelionMusic) can do that automatically.
