### ISSUE TITLE
Error when i opening run.py

### ISSUE THREAD

**Issue by NullPointerExceptionBruh** [Raptor123471/DingoLingo#137]
D:\Veli\DingoLingo-master\musicbot\linkutils.py:18: SyntaxWarning: invalid escape sequence '\('
  "http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+")
D:\Veli\DingoLingo-master\musicbot\linkutils.py:124: SyntaxWarning: invalid escape sequence '\('
  "http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+")
Traceback (most recent call last):
  File "D:\Veli\DingoLingo-master\run.py", line 84, in <module>
    bot.run(config.BOT_TOKEN, bot=True, reconnect=True)
  File "C:\Program Files\Python312\Lib\site-packages\discord\client.py", line 766, in run
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\discord\client.py", line 745, in runner
    await self.start(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Client.start() got an unexpected keyword argument 'bot'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000021C18C60740>
Why i get this error?

**Comment by NullPointerExceptionBruh** [comment]
i fixed it removing bot= true in run.py
