### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by dabmaster40** [Raptor123471/DingoLingo#57]
I have a fork of this bot mixed with my own things in several servers. It keeps giving me this error and then won't connect to voice channel in half of the servers it is in. 

Traceback (most recent call last):
  File "/home/container/.local/lib/python3.9/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/home/container/main.py", line 63, in on_ready
    await register(guild)
  File "/home/container/main.py", line 110, in register
    await guild.me.edit(nick=sett.get('default_nickname'))
  File "/home/container/.local/lib/python3.9/site-packages/discord/member.py", line 637, in edit
    await http.change_my_nickname(guild_id, nick, reason=reason)
  File "/home/container/.local/lib/python3.9/site-packages/discord/http.py", line 248, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

**Comment by Raptor123471** [comment]
The nickname set in line 63 of `run.py` is throwing an exception because of permissions causing the rest of the register method to stop early. This nickname set needs exception handling.

**Comment by sam1e-dev** [comment]
I am also experiencing this

**Comment by dabmaster40** [comment]
has this been fixed yet?

**Comment by Sarge1305** [comment]
I'm facing this issue as well. Is there any temporary fix that I can do to avoid this issue?

**Comment by dabmaster40** [comment]
this is what i did for mine to solve it 

    try:
      await guild.me.edit(nick=sett.get('default_nickname'))
    except:
      return

**Comment by Raptor123471** [comment]
Fix is in master branch.
